site_name: Delphix Masking 5.3
theme: 
  name: material
  custom_dir: 'material/'
  palette:
    primary: 
    accent: 
  logo: 'images/delphix-logo-white.png'
  favicon: 'images/logo.png'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - meta

plugins:
  - search
  - awesome-pages
