site_name: Delphix Masking 5.3
theme: 
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'light blue'
  logo: 
    icon: 'library_books'
  favicon: 'images/logo.png'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - meta

plugins:
  - search
  - awesome-pages
